### ISSUE TITLE
Mystery Pipe in Las Vegas

### ISSUE THREAD

**Issue by ericdalpe** [AguaClara/aide_template#27]
When I was in Las Vegas I took a picture of this horizontal pipe, which wraps around the base of the filter control box.
![image](https://user-images.githubusercontent.com/35944788/52815475-c74fae80-306c-11e9-8630-b16fe43626d5.png)
![image](https://user-images.githubusercontent.com/35944788/52815494-cdde2600-306c-11e9-889c-51d4a915684b.png)

But then when I looked at the AutoCAD model, the pipe was not there.

![image](https://user-images.githubusercontent.com/35944788/52815416-a5eec280-306c-11e9-8812-ace2e7ca18dc.png)

What is this pipe? How should we be including it?

**Comment by monroews** [comment]
I believe this is the pipe that takes the treated water to the distribution tank. It hasn't been included in our designs because it requires a hydraulic design based on where it is taking the water and we don't have that information when we are initially drawing our designs. I'd suggest that it is a low priority.
